apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoservice-dply
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demoservice
  replicas: 1
  template:
    metadata:
      labels:
        app: demoservice
    spec:
      containers:
      - name: demoservice
        image: micaelgallego/demoservice-k8s2:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demoservice-service
  labels:
    app: demoservice
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: demoservice-port
  selector:
    app: demoservice
  type: NodePort